sudo: false

services:
    - docker

language: go

go:
    - 1.13.7

cache:
  directories:
    - .cache
    - $HOME/.build
    - $HOME/go/pkg/mod
    - $HOME/go/bin

stages:
    - build and test
    - build release
    - publish image

jobs:
  include:
    - stage: build and test
      name: lint
      script:
        - make lint
        - make tidy-check
        - shellcheck script/*/*.sh
        - shellcheck .travis/*.sh
    - stage: build and test
      name: linux build and test
      script:
        - make build
        - make test
      os: linux
      dist: xenial
    - stage: build and test
      name: macos build and test
      script:
        - make build
        - make test
      os: macos
    - stage: build release
      script:
        - .travis/build-release.sh
      os: linux
      dist: xenial
      deploy:
        - provider: releases
          api_key: $GITHUB_TOKEN
          file_glob: true
          file: releases/*
          skip_cleanup: true
          on:
            tags: true
            condition: $GITHUB_TOKEN != ""
    - stage: publish image
      if: type = push AND (tag IS present OR branch = master)
      os: linux
      dist: xenial
      before_script:
        # Decrypt credentials needed to log into gcr registry
        - openssl aes-256-cbc -K $encrypted_b48f9e852489_key -iv $encrypted_b48f9e852489_iv -in .travis/spire-travis-ci.json.enc -out .travis/spire-travis-ci.json -d
      script:
        - make image
        - .travis/publish-images.sh
